batch_size: 24
data_folder: /scratch.ssd/jmatouse/job_6963757.pbs-m1.metacentrum.cz/cz-wikipedia.processed
dataset_params:
  max_mel_length: 512
  phoneme_mask_prob: 0.1
  replace_prob: 0.2
  symbol_dict_path: symbol_dict.csv
  token_maps: token_maps.pkl
  token_mask: M
  token_separator: ' '
  tokenizer: fav-kky/FERNET-C5
  word_mask_prob: 0.15
  word_separator: 18065
log_dir: models/cs-wikipedia
log_interval: 10
mixed_precision: fp16
model_params:
  dropout: 0.1
  hidden_size: 768
  intermediate_size: 2048
  max_position_embeddings: 512
  num_attention_heads: 12
  num_hidden_layers: 12
  vocab_size: 81
num_process: 1
num_steps: 8000000
save_interval: 50000
